services:
  - type: web
    name: cloth-counter-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: 'postgresql://postgres:LQprg89gLbpe536w@db.fddkwulxkkgszcqwfccv.supabase.co:5432/postgres'
      - key: NODE_ENV
        value: production